language: java
notifications:
  email: false

jdk:
  - oraclejdk8

services:
  - mysql

before_script:
  - mysql -u root -e 'CREATE DATABASE mundus;'
  - mysql -u root mundus < mundus.sql

script:
- "mvn install -DskipTests=false"
- "mvn site"
- "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)